name: build and push

#Controls when the workflow will run
on:
#  Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-test
    
    
    steps:
      -
        name: checkout
        uses: actions/chekout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
      -
        name: Pull Trigger
        run: |
          curl -X POST ${{ secrets.DOCKER_PULL_TRIGGER_URL }} \
          --data image=${{ secrets.DOCKER_IMAGE }} \
          --data port=8081 \
          --data targetPort=3000
        
